### ISSUE TITLE
Error when a config file cannot be found

### ISSUE THREAD

**Issue by tdealtry** [ToolDAQ/ToolDAQApplication#5]
If would be nice if there was an error when a config file in ToolsConfig is missing. For example, this should be an error
`wcsim1 WCSimReader configfiles/WCSimReaderToolConfig`
And this should run
`wcsim1 WCSimReader configfiles/WCSimReaderTest/WCSimReaderToolConfig`

Of course tools should check their options exist during initialisation, but some might prefer to use lots of defaults...

**Comment by brichards64** [comment]
Hi Tom,

Iv edited the core framework to give a warning if a non valid config file path is given (rather than an error).

The default behaviour would therefore be to keep operating if the file isnt present allowing nulls strings and transient files to exist. If something is mission critical as you say the individual tool can implement checks on the presence of the variables.
